services:
  db:
    image: postgres:15.2
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data-managementsystem:/var/lib/postgresql/data
    networks:
      - springboot-network

  app:
    build: .
    ports:
      - "8081:8081"
    environment:
      APP_NAME: ${APP_NAME}
      APP_PORT: ${APP_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_URL: ${DB_URL}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_APP_NAME: ${JWT_APP_NAME}
      JWT_EXPIRE_TIME: ${JWT_EXPIRE_TIME}
      DDL_AUTO: ${DDL_AUTO}
      SHOW_SQL: ${SHOW_SQL}
      API_DOCS: ${API_DOCS}
    depends_on:
      - db
    volumes:
      # - assets-volume:/app/src/main/resources/static/assets/
      - ./src/main/resources/static/assets:/app/src/main/resources/static/assets
    networks:
      - springboot-network

volumes:
  postgres-data-managementsystem:
    driver: local

  # assets-volume:
  #   driver: local


networks:
  springboot-network:
    driver: bridge
